#!/usr/bin/env bash
# argumented input from users to copy values.
# the number of arguments are four.
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp connects with
# The path to the SSH private key that scp uses
if [ ! -z -lt $5 ];
then
    scp $1 $2@$3:~/ $4
fi

