#!/usr/bin/env bash
# script that configures a new Ubuntu machine to install nginx server
ssh ubuntu@44.197.251.60 'sudo apt-get -y install nginx --allow-downgrades'
ssh ubuntu@44.197.251.60 'echo "Hello World!" >> /var/www/html/index.nginx-debian.html'
shh ubuntu@44.197.251.60 'sudo ufw -y enable'''
ssh ubuntu@44.197.251.60 'sudo services nginx start'
