#!/usr/bin/env bash
# script that configures a new Ubuntu machine to install nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" >> /var/www/html/index.nginx.debian.html
sudo service nginx start
sudo service nginx status

