#!/usr/bin/env bash
# Installing mysql ver 5.7.* specifically

sudo echo "\
deb http://repo.mysql.com/apt/ubuntu/ bionic mysql-apt-config
deb http://repo.mysql.com/apt/ubuntu/ bionic mysql-5.7
deb http://repo.mysql.com/apt/ubuntu/ bionic mysql-tools
deb-src http://repo.mysql.com/apt/ubuntu/ bionic mysql-5.7
" | sudo tee -a /etc/apt/sources.list.d/mysql.list

# to avoid being upgraded to a highr version 
sudo echo "\
Package: mysql-server
Pin: version 5.7.*
Pin-Priority: 1001
Package: mysql-client
Pin: version 5.7.*
Pin-Priority: 1001
Package: mysql-community-server
Pin: version 5.7.*
Pin-Priority: 1001
Package: mysql-community-client
Pin: version 5.7.*
Pin-Priority: 1001
" | sudo tee -a /etc/apt/preferences.d/mysql

# handling signature couldn't be verified just incase
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29

# Installing updates
sudo apt-get update

# Installing mysql 5.7.*
apt-get install mysql-client mysql-server
