#!/usr/bin/env bash
# Bash script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

while true
do
	echo "to infinity and beyond"
	sleep 2
	if (( trap == SIGTERM ))
	then
		echo "I am invincible!!!"
	fi
done
