#!/usr/bin/env bash
# Fizzbuzz challenge for multiples of 3, 5 and 15

for (( I=1 ; I<100 ; I++ ))
do
	if (( $I%15 ==  0 ))
	then
		echo "FizzBuzz"
	elif (( $I%5 == 0 ))
	then
		echo "Buzz"
	elif (( $I%3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$I"
	fi
done
