#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

I=1
while [ $I -lt 10 ]
do	
	if [ $I -eq 9 ]
	then
		echo 'Hi'
	fi
	echo 'Best School'
	I=$(( I+1 ))
done
