#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
# Requirements:
# You must use the while loop (for and until are forbidden)

HRS=0
while [ $HRS -lt 13 ]
do
	echo "Hour: $HRS"
	MIN=1
	while [ $MIN -lt 60 ]
	do
		echo "$MIN"
		MIN=$(( MIN+1 ))
	done
	HRS=$(( HRS+1 ))
done
