#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
# Requirements:
# You must use the for loop (while and until are forbidden)
# Do not display hidden files

LIST="$(ls)"
for a in $LIST
do
	if [ "$a" ]
	then
		echo "$a" | cut -d '-' -f2
	fi
done
