#!/usr/bin/env bash
# installing ufw in the load balancer
apt-get -y update
apt-get -y install ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw 80/tcp
ufw reload
ufw status
